version: "3.8"

services:
    dnsdock:
        image: aacebedo/dnsdock:latest-amd64
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - 172.17.0.1:53:53/udp
    starter:
        build: .
        environment:
            - APP_URL=http://starter.uspdev.docker:8000
            - SENHAUNICA_DEV="http://senhaunica.uspdev.docker:8000/wsusuario/oauth"
            - DB_CONNECTION=mariadb
            - DB_HOST=mariadb.uspdev.docker
            - DB_DATABASE=starter
            - DB_USERNAME=root
            - DB_PASSWORD=alfafa
            - DNSDOCK_NAME=starter
            - DNSDOCK_IMAGE=uspdev
        depends_on:
            - mariadb
            - senhaunica
    mariadb:
        image: mariadb
        environment:
            - MARIADB_DATABASE=starter
            - MARIADB_ROOT_PASSWORD=alfafa
            - DNSDOCK_NAME=mariadb
            - DNSDOCK_IMAGE=uspdev
    senhaunica:
        image: faker
        environment:
            - APP_URL=http://senhaunica.uspdev.docker:8000
            - DNSDOCK_NAME=senhaunica
            - DNSDOCK_IMAGE=uspdev
